### ISSUE TITLE
Password/Applying money changes

### ISSUE THREAD

**Issue by Kryptedbbkick** [Jarrrk/AltisWebmin#2]
Hello so for the first thing how can we change the password i have looked through every files code and see where password is read but changing it has not shown up. and applying changes to the edit of a players bank account will ends at a 404 error saying the file used for applying it is missing and from what it seems is that it actually is.

**Comment by Jarrrk** [comment]
Hi mate,

This project hasn't been updated in 3 years, AltisLife has since changed its DB schema making this project no longer up to date.

If you're still wanting a solution similar to this, I'm always available for hire.

**Comment by Kryptedbbkick** [comment]
No need im a programmer ill just write a custom one for myself instead of
using theres.
