### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bladadah916** [Jarrrk/AltisWebmin#4]
I get this error but I do not know how to unblock myself.

Your network has been suspended due to too many invalid login attempts, please see the administrator of the website to be unblocked.

**Comment by Jarrrk** [comment]
> Your network has been suspended due to too many invalid login attempts, please see the administrator of the website to be unblocked.

Well first of all that sounds like a hosting issue.

Secondly, this project hasn't been updated in 3 years, AltisLife has since changed its DB schema making this project no longer up to date.

If you're still wanting a solution similar to this, I'm always available for hire.
